# created by btcontrol make install, hostname lower case 
    #$HTTP["host"] != "dietpi" { 
    #     url.redirect = ("" => "http://dietpi/") 
    # } 
    # fürs capture portal: 
    # server.error-handler-404   = "/index.html" 
$HTTP["host"] !~ "^192\.168\." {
    url.rewrite-if-not-file = (
        "^/(.*)$" => "/index.html"
    )
}
